require 'json'

module ApiSpec; end

require 'generator'

require 'specs/basic_pages'
require 'specs/blog_posts'
require 'specs/blogs'
require 'specs/calendars'
require 'specs/campaign_data'
require 'specs/contacts'
require 'specs/donations'
require 'specs/events'
require 'specs/imports'
require 'specs/exports'
require 'specs/lists'
require 'specs/memberships'
require 'specs/page_attachments'
require 'specs/people'
require 'specs/people_tags'
require 'specs/sites'
require 'specs/survey_responses'
require 'specs/surveys'
require 'specs/webhooks'
